### ISSUE TITLE
Using with images on CDN?

### ISSUE THREAD

**Issue by uclajames** [Retina-Images/Retina-Images#25]
Is it possible to use Retina Images with images that are hosted from a separate domain? We have a separate domain that we use to serve our static content from (CDN style). So I'm just trying to figure out how I could use Retina Images on a configuration like that and where the various pieces of Retina Images would go.

**Comment by tigranpetrossian** [comment]
@ofirbaruch Any news on the topic?

**Comment by jeremyworboys** [comment]
@tigranpetrossian I received the modifications form Ofir, but haven't had a chance to review them thoroughly at this point.

**Comment by uclajames** [comment]
I see this issue is closed. Was a solution found? If so, how does it work?

**Comment by jeremyworboys** [comment]
I don't remember ever reaching a solution to this issue. Ofir linked to code hosted on a domain that is no longer registered so I am not able to see their modifications anymore to determine if there was a viable solution there.

@ofirbaruch Are you still have access to your modifications that you could share again?
