### ISSUE TITLE
Code does not fall back to 2x image if 3x image does not exist

### ISSUE THREAD

**Issue by BattyBlogger** [Retina-Images/Retina-Images#36]
Hello, I noticed my site, which uses the Retina-Images code, does not serve Retina images to the iPhone 6 Plus. Looking at the code, I believe this is due to a bug where if the client device is 3x-capable and the server does not have a 3x image, but the server does have a 2x image, the code falls all the way back to the base 1x image instead of sending the 2x image, which is what I would expect the code to do.

The end result is that the iPhone 6 Plus gets the 1x image and looks worse than older iPhones which get the 2x image. I don't think it's reasonable for me to have to create a 3x image right now to work around this issue since 3x images consume a lot of resources and I would have to retroactively create 3x images for the many older images on my site.

**Comment by jeremyworboys** [comment]
Hey @BattyBlogger, I just pushed version 1.7.0 which should fix this issue.
