### ISSUE TITLE
Sending @3x instead of @2x

### ISSUE THREAD

**Issue by davidrossiter** [Retina-Images/Retina-Images#40]
Hello, I am finding that the @3x image is being sent when the @2x should be.  

An example of my logs are below. I am completely stumped as to why, is there any obvious error I might have made or overlooked that someone may have had before too?

	Array
	(
	    [__utma] => 176504032.1247276052.1426926196.1432030676.1432033220.263
	    [__utmz] => 176504032.1427998243.3.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
	    [PHPSESSID] => fe5537dfe68eddd94efd2718cf5b58be
	    [__utmc] => 176504032
	    [NREUM] => h=1432033258072&r=36527&p=36527
	    [devicePixelRatio] => 2
	    [__utmb] => 176504032.2.10.1432033220
	    [__utmt] => 1
	)

	document_root:     /home/public_html
	requested_uri:     /images/user_images/4/21/4-1431962841.jpg
	requested_file:    4-1431962841.jpg
	source_file:       /home/public_html/images/user_images/4/21/4-1431962841.jpg
	source_ext:        jpg
	@2x_file:          /home/public_html/images/user_images/4/21/4-1431962841@2x.jpg
	@3x_file:          /home/public_html/images/user_images/4/21/4-1431962841@3x.jpg
	devicePixelRatio:  2
	cache_directive:   must-revalidate
	sending file:      /home/public_html/images/user_images/4/21/4-1431962841@3x.jpg

	Array
	(
	    [__utma] => 176504032.1247276052.1426926196.1432030676.1432033220.263
	    [__utmz] => 176504032.1427998243.3.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)
	    [PHPSESSID] => fe5537dfe68eddd94efd2718cf5b58be
	    [__utmc] => 176504032
	    [NREUM] => h=1432033312161&r=36527&p=36527
	    [devicePixelRatio] => 2
	    [__utmb] => 176504032.5.10.1432033220
	    [__utmt] => 1
	)

	document_root:     /home/public_html
	requested_uri:     /images/photos/2mBjFyn3hI/424/_2mBjFyn3hI.jpg
	requested_file:    2mBjFyn3hI.jpg
	source_file:       /home/public_html/images/photos/2mBjFyn3hI/424/2mBjFyn3hI.jpg
	source_ext:        jpg
	@2x_file:          /home/public_html/images/photos/2mBjFyn3hI/424/2mBjFyn3hI@2x.jpg
	@3x_file:          /home/public_html/images/photos/2mBjFyn3hI/424/2mBjFyn3hI@3x.jpg
	devicePixelRatio:  2
	cache_directive:   must-revalidate
	sending file:      /home/public_html/images/photos/2mBjFyn3hI/424/2mBjFyn3hI@3x.jpg

Thanks for any help!

**Comment by jeremyworboys** [comment]
Hi @davidrossiter 

There was a bug introduced in version 1.7.1 that caused this. It should have been patched in 1.7.2 which was released yesterday. 

Let me know if you are still having issues with 1.7.2.

**Comment by davidrossiter** [comment]
Hey @jeremyworboys Brilliant, that fixed it, thanks for getting back with help so quickly!

**Comment by jeremyworboys** [comment]
No worries. Happy to help.
