### ISSUE TITLE
set cookie only once

### ISSUE THREAD

**Issue by staabm** [Retina-Images/Retina-Images#41]
Why does the suggested Javascript markup send the ajax request / set the cookie manually on every page request? when the cookie is already existent from a previous visit this codes can just do nothing?

```html
<script>(function(w){var dpr=((w.devicePixelRatio===undefined)?1:w.devicePixelRatio);if(!!w.navigator.standalone){var r=new XMLHttpRequest();r.open('GET','/retinaimages.php?devicePixelRatio='+dpr,false);r.send()}else{document.cookie='devicePixelRatio='+dpr+'; path=/'}})(window)</script>
```

**Comment by jeremyworboys** [comment]
An XHR is not made for regular visitors to your site at any time. 

The XHR is behind the `if(!!w.navigator.standalone)` conditional which is `true` for when Safari is generating the website preview thumbnails.

![screen shot 2015-06-25 at 7 02 06 pm](https://cloud.githubusercontent.com/assets/988173/8350904/ba038648-1b6c-11e5-8a94-c5d56c1307e4.png)
